[{:wps-beacon-ie {:ie-key-wps-sc-state 2},
  :age 0,
  :ssid "<data>",
  :ht-caps-ie
                 {:ampdu-params 27,
                  :asel-caps 0,
                  :caps 6174,
                  :ext-caps 0,
                  :mcs-set "<data>",
                  :txbf-caps 0},
  :bssid "a4:b1:e9:71:3e:5",
  :rates (1 2 5 11 18 24 36 54 6 9 12 48),
  :ssid-str "ARRAN",
  :wpa-ie
                 {:ie-key-wpa-authsels (2),
                  :ie-key-wpa-mcipher 2,
                  :ie-key-wpa-uciphers (2),
                  :ie-key-wpa-version 1},
  :capabilities 1041,
  :beacon-int 100,
  :channel-flags 10,
  :ap-mode 2,
  :rssi -2,
  :channel 6,
  :rsn-ie
                 {:ie-key-rsn-authsels (2),
                  :ie-key-rsn-caps
                                       {:gtksa-replay-counters 1,
                                        :no-pairwise false,
                                        :pre-auth false,
                                        :ptksa-replay-counters 16},
                  :ie-key-rsn-mcipher 2,
                  :ie-key-rsn-uciphers (4),
                  :ie-key-rsn-version 1},
  :ie "<data>",
  :noise -92,
  :ht-ie
                 {:ht-service-int 0,
                  :ht-obss-non-ht-stas-present false,
                  :ht-non-gf-stas-present true,
                  :ht-secondary-chan-offset 0,
                  :ht-primary-chan 6,
                  :ht-secondary-beacon false,
                  :ht-basic-mcs-set "<data>",
                  :ht-pco-active false,
                  :ht-rifs-mode true,
                  :ht-dual-cts-prot false,
                  :ht-tx-burst-limit false,
                  :ht-sta-chan-width false,
                  :ht-psmp-stas-only false,
                  :ht-pco-phase false,
                  :ht-dual-beacon false,
                  :ht-op-mode 0,
                  :ht-lsig-txop-prot-full false}}
 {:wps-beacon-ie {:ie-key-wps-sc-state 2},
  :age 0,
  :ssid "<data>",
  :ht-caps-ie
                 {:ampdu-params 27,
                  :asel-caps 0,
                  :caps 6174,
                  :ext-caps 0,
                  :mcs-set "<data>",
                  :txbf-caps 0},
  :bssid "a4:b1:e9:4d:3d:9",
  :rates (1 2 5 11 18 24 36 54 6 9 12 48),
  :ssid-str "BARRA",
  :wpa-ie
                 {:ie-key-wpa-authsels (2),
                  :ie-key-wpa-mcipher 2,
                  :ie-key-wpa-uciphers (2),
                  :ie-key-wpa-version 1},
  :capabilities 1041,
  :beacon-int 100,
  :channel-flags 524,
  :ap-mode 2,
  :rssi -2,
  :channel 6,
  :rsn-ie
                 {:ie-key-rsn-authsels (2),
                  :ie-key-rsn-caps
                                       {:gtksa-replay-counters 1,
                                        :no-pairwise false,
                                        :pre-auth false,
                                        :ptksa-replay-counters 16},
                  :ie-key-rsn-mcipher 2,
                  :ie-key-rsn-uciphers (4),
                  :ie-key-rsn-version 1},
  :ie "<data>",
  :noise -92,
  :ht-ie
                 {:ht-service-int 0,
                  :ht-obss-non-ht-stas-present true,
                  :ht-non-gf-stas-present true,
                  :ht-secondary-chan-offset 1,
                  :ht-primary-chan 6,
                  :ht-secondary-beacon false,
                  :ht-basic-mcs-set "<data>",
                  :ht-pco-active false,
                  :ht-rifs-mode true,
                  :ht-dual-cts-prot false,
                  :ht-tx-burst-limit false,
                  :ht-sta-chan-width true,
                  :ht-psmp-stas-only false,
                  :ht-pco-phase false,
                  :ht-dual-beacon false,
                  :ht-op-mode 2,
                  :ht-lsig-txop-prot-full false}}
 {:age 0,
  :ssid "<data>",
  :ht-caps-ie
   {:ampdu-params 27,
    :asel-caps 0,
    :caps 6174,
    :ext-caps 0,
    :mcs-set "<data>",
    :txbf-caps 0},
  :bssid "a4:b1:e9:4c:f3:b5",
  :rates (1 2 5 11 18 24 36 54 6 9 12 48),
  :ssid-str "SKYE",
  :wpa-ie
   {:ie-key-wpa-authsels (2),
    :ie-key-wpa-mcipher 2,
    :ie-key-wpa-uciphers (2),
    :ie-key-wpa-version 1},
  :capabilities 1041,
  :beacon-int 100,
  :channel-flags 524,
  :ap-mode 2,
  :rssi -2,
  :channel 6,
  :rsn-ie
   {:ie-key-rsn-authsels (2),
    :ie-key-rsn-caps
                         {:gtksa-replay-counters 1,
                          :no-pairwise false,
                          :pre-auth false,
                          :ptksa-replay-counters 16},
    :ie-key-rsn-mcipher 2,
    :ie-key-rsn-uciphers (4),
    :ie-key-rsn-version 1},
  :ie "<data>",
  :wps-prob-resp-ie
   {:ie-key-wps-cfg-methods 132,
    :ie-key-wps-manufacturer "Technicolor",
    :ie-key-wps-dev-name-data "<data>",
    :ie-key-wps-sc-state 2,
    :ie-key-wps-uuid-e "<data>",
    :ie-key-wps-dev-name "Technicolor TG582n",
    :ie-key-wps-model-num "582n",
    :ie-key-wps-resp-type 3,
    :ie-key-wps-sel-reg false,
    :ie-key-wps-serial-num "1236WFPUH",
    :ie-key-wps-model-name "Technicolor TG",
    :ie-key-wps-rf-bands 1,
    :ie-key-wps-primary-dev-type
     {:wps-dev-type-cat 6,
      :wps-dev-type-oui "<data>",
      :wps-dev-type-sub-cat 1}},
  :noise -92,
  :ht-ie
   {:ht-service-int 0,
    :ht-obss-non-ht-stas-present true,
    :ht-non-gf-stas-present true,
    :ht-secondary-chan-offset 1,
    :ht-primary-chan 6,
    :ht-secondary-beacon false,
    :ht-basic-mcs-set "<data>",
    :ht-pco-active false,
    :ht-rifs-mode true,
    :ht-dual-cts-prot false,
    :ht-tx-burst-limit false,
    :ht-sta-chan-width true,
    :ht-psmp-stas-only false,
    :ht-pco-phase false,
    :ht-dual-beacon false,
    :ht-op-mode 2,
    :ht-lsig-txop-prot-full false}}
 {:age 0,
  :ssid "<data>",
  :ht-caps-ie
   {:ampdu-params 27,
    :asel-caps 0,
    :caps 6174,
    :ext-caps 0,
    :mcs-set "<data>",
    :txbf-caps 0},
  :bssid "a4:b1:e9:4c:b8:b5",
  :rates (1 2 5 11 18 24 36 54 6 9 12 48),
  :ssid-str "SHETLAND",
  :wpa-ie
   {:ie-key-wpa-authsels (2),
    :ie-key-wpa-mcipher 2,
    :ie-key-wpa-uciphers (2),
    :ie-key-wpa-version 1},
  :capabilities 1041,
  :beacon-int 100,
  :channel-flags 524,
  :ap-mode 2,
  :rssi -2,
  :channel 6,
  :rsn-ie
   {:ie-key-rsn-authsels (2),
    :ie-key-rsn-caps
                         {:gtksa-replay-counters 1,
                          :no-pairwise false,
                          :pre-auth false,
                          :ptksa-replay-counters 16},
    :ie-key-rsn-mcipher 2,
    :ie-key-rsn-uciphers (4),
    :ie-key-rsn-version 1},
  :ie "<data>",
  :wps-prob-resp-ie
   {:ie-key-wps-cfg-methods 132,
    :ie-key-wps-manufacturer "Technicolor",
    :ie-key-wps-dev-name-data "<data>",
    :ie-key-wps-sc-state 2,
    :ie-key-wps-uuid-e "<data>",
    :ie-key-wps-dev-name "Technicolor TG582n",
    :ie-key-wps-model-num "582n",
    :ie-key-wps-resp-type 3,
    :ie-key-wps-sel-reg false,
    :ie-key-wps-serial-num "1236WFYBL",
    :ie-key-wps-model-name "Technicolor TG",
    :ie-key-wps-rf-bands 1,
    :ie-key-wps-primary-dev-type
     {:wps-dev-type-cat 6,
      :wps-dev-type-oui "<data>",
      :wps-dev-type-sub-cat 1}},
  :noise -92,
  :ht-ie
   {:ht-service-int 0,
    :ht-obss-non-ht-stas-present true,
    :ht-non-gf-stas-present true,
    :ht-secondary-chan-offset 1,
    :ht-primary-chan 6,
    :ht-secondary-beacon false,
    :ht-basic-mcs-set "<data>",
    :ht-pco-active false,
    :ht-rifs-mode true,
    :ht-dual-cts-prot false,
    :ht-tx-burst-limit false,
    :ht-sta-chan-width true,
    :ht-psmp-stas-only false,
    :ht-pco-phase false,
    :ht-dual-beacon false,
    :ht-op-mode 2,
    :ht-lsig-txop-prot-full false}}
 {:age 0,
  :ssid "<data>",
  :ht-caps-ie
   {:ampdu-params 27,
    :asel-caps 0,
    :caps 6174,
    :ext-caps 0,
    :mcs-set "<data>",
    :txbf-caps 0},
  :bssid "a4:b1:e9:4c:fb:1",
  :rates (1 2 5 11 18 24 36 54 6 9 12 48),
  :ssid-str "ORKNEY",
  :wpa-ie
   {:ie-key-wpa-authsels (2),
    :ie-key-wpa-mcipher 2,
    :ie-key-wpa-uciphers (2),
    :ie-key-wpa-version 1},
  :capabilities 1041,
  :beacon-int 100,
  :channel-flags 10,
  :ap-mode 2,
  :rssi -2,
  :channel 6,
  :rsn-ie
   {:ie-key-rsn-authsels (2),
    :ie-key-rsn-caps
                         {:gtksa-replay-counters 1,
                          :no-pairwise false,
                          :pre-auth false,
                          :ptksa-replay-counters 16},
    :ie-key-rsn-mcipher 2,
    :ie-key-rsn-uciphers (4),
    :ie-key-rsn-version 1},
  :ie "<data>",
  :wps-prob-resp-ie
   {:ie-key-wps-cfg-methods 132,
    :ie-key-wps-manufacturer "Technicolor",
    :ie-key-wps-dev-name-data "<data>",
    :ie-key-wps-sc-state 2,
    :ie-key-wps-uuid-e "<data>",
    :ie-key-wps-dev-name "Technicolor TG582n",
    :ie-key-wps-model-num "582n",
    :ie-key-wps-resp-type 3,
    :ie-key-wps-sel-reg false,
    :ie-key-wps-serial-num "1236WFQPT",
    :ie-key-wps-model-name "Technicolor TG",
    :ie-key-wps-rf-bands 1,
    :ie-key-wps-primary-dev-type
     {:wps-dev-type-cat 6,
      :wps-dev-type-oui "<data>",
      :wps-dev-type-sub-cat 1}},
  :noise -92,
  :ht-ie
   {:ht-service-int 0,
    :ht-obss-non-ht-stas-present false,
    :ht-non-gf-stas-present false,
    :ht-secondary-chan-offset 0,
    :ht-primary-chan 6,
    :ht-secondary-beacon false,
    :ht-basic-mcs-set "<data>",
    :ht-pco-active false,
    :ht-rifs-mode true,
    :ht-dual-cts-prot false,
    :ht-tx-burst-limit false,
    :ht-sta-chan-width false,
    :ht-psmp-stas-only false,
    :ht-pco-phase false,
    :ht-dual-beacon false,
    :ht-op-mode 0,
    :ht-lsig-txop-prot-full false}}
 {:age 0,
  :ssid "<data>",
  :ht-caps-ie
   {:ampdu-params 27,
    :asel-caps 0,
    :caps 6174,
    :ext-caps 0,
    :mcs-set "<data>",
    :txbf-caps 0},
  :bssid "a4:b1:e9:7b:cf:f5",
  :rates (1 2 5 11 18 24 36 54 6 9 12 48),
  :ssid-str "SLC",
  :wpa-ie
   {:ie-key-wpa-authsels (2),
    :ie-key-wpa-mcipher 2,
    :ie-key-wpa-uciphers (2),
    :ie-key-wpa-version 1},
  :capabilities 1041,
  :beacon-int 100,
  :channel-flags 524,
  :ap-mode 2,
  :rssi -2,
  :channel 6,
  :rsn-ie
   {:ie-key-rsn-authsels (2),
    :ie-key-rsn-caps
                         {:gtksa-replay-counters 1,
                          :no-pairwise false,
                          :pre-auth false,
                          :ptksa-replay-counters 16},
    :ie-key-rsn-mcipher 2,
    :ie-key-rsn-uciphers (4),
    :ie-key-rsn-version 1},
  :ie "<data>",
  :wps-prob-resp-ie
   {:ie-key-wps-cfg-methods 132,
    :ie-key-wps-manufacturer "Technicolor",
    :ie-key-wps-dev-name-data "<data>",
    :ie-key-wps-sc-state 2,
    :ie-key-wps-uuid-e "<data>",
    :ie-key-wps-dev-name "Technicolor TG582n",
    :ie-key-wps-model-num "582n",
    :ie-key-wps-resp-type 3,
    :ie-key-wps-sel-reg false,
    :ie-key-wps-serial-num "1249VFLAN",
    :ie-key-wps-model-name "Technicolor TG",
    :ie-key-wps-rf-bands 1,
    :ie-key-wps-primary-dev-type
     {:wps-dev-type-cat 6,
      :wps-dev-type-oui "<data>",
      :wps-dev-type-sub-cat 1}},
  :noise -92,
  :ht-ie
   {:ht-service-int 0,
    :ht-obss-non-ht-stas-present false,
    :ht-non-gf-stas-present false,
    :ht-secondary-chan-offset 1,
    :ht-primary-chan 6,
    :ht-secondary-beacon false,
    :ht-basic-mcs-set "<data>",
    :ht-pco-active false,
    :ht-rifs-mode true,
    :ht-dual-cts-prot false,
    :ht-tx-burst-limit false,
    :ht-sta-chan-width true,
    :ht-psmp-stas-only false,
    :ht-pco-phase false,
    :ht-dual-beacon false,
    :ht-op-mode 0,
    :ht-lsig-txop-prot-full false}}
 {:age 0,
  :ssid "<data>",
  :ht-caps-ie
   {:ampdu-params 27,
    :asel-caps 0,
    :caps 6174,
    :ext-caps 0,
    :mcs-set "<data>",
    :txbf-caps 0},
  :bssid "a4:b1:e9:7b:ac:a9",
  :rates (1 2 5 11 18 24 36 54 6 9 12 48),
  :ssid-str "ThoughtWorks",
  :wpa-ie
   {:ie-key-wpa-authsels (2),
    :ie-key-wpa-mcipher 2,
    :ie-key-wpa-uciphers (2),
    :ie-key-wpa-version 1},
  :capabilities 1041,
  :beacon-int 100,
  :channel-flags 524,
  :ap-mode 2,
  :rssi -2,
  :channel 6,
  :rsn-ie
   {:ie-key-rsn-authsels (2),
    :ie-key-rsn-caps
                         {:gtksa-replay-counters 1,
                          :no-pairwise false,
                          :pre-auth false,
                          :ptksa-replay-counters 16},
    :ie-key-rsn-mcipher 2,
    :ie-key-rsn-uciphers (4),
    :ie-key-rsn-version 1},
  :ie "<data>",
  :wps-prob-resp-ie
   {:ie-key-wps-cfg-methods 132,
    :ie-key-wps-manufacturer "Technicolor",
    :ie-key-wps-dev-name-data "<data>",
    :ie-key-wps-sc-state 2,
    :ie-key-wps-uuid-e "<data>",
    :ie-key-wps-dev-name "Technicolor TG582n",
    :ie-key-wps-model-num "582n",
    :ie-key-wps-resp-type 3,
    :ie-key-wps-sel-reg false,
    :ie-key-wps-serial-num "1249VFP2M",
    :ie-key-wps-model-name "Technicolor TG",
    :ie-key-wps-rf-bands 1,
    :ie-key-wps-primary-dev-type
     {:wps-dev-type-cat 6,
      :wps-dev-type-oui "<data>",
      :wps-dev-type-sub-cat 1}},
  :noise -92,
  :ht-ie
   {:ht-service-int 0,
    :ht-obss-non-ht-stas-present true,
    :ht-non-gf-stas-present false,
    :ht-secondary-chan-offset 1,
    :ht-primary-chan 6,
    :ht-secondary-beacon false,
    :ht-basic-mcs-set "<data>",
    :ht-pco-active false,
    :ht-rifs-mode true,
    :ht-dual-cts-prot false,
    :ht-tx-burst-limit false,
    :ht-sta-chan-width true,
    :ht-psmp-stas-only false,
    :ht-pco-phase false,
    :ht-dual-beacon false,
    :ht-op-mode 2,
    :ht-lsig-txop-prot-full false}}]